mi_topic: "/mi"
p_not_measured_topic: "/p_not_measured"
mi_max_topic: "/mi_max"
map_topic: "/map"
click_topic: "/clicked_point"

poisson_rate: 0.01
mi_angular_steps: 100
mi_spatial_steps: 100
unknown_threshold: 0.1
beam_independence: true
