mi_topic: "/mi"
p_not_measured_topic: "/p_not_measured"
map_topic: "/map"
click_topic: "/clicked_point"

poisson_rate: 0.3
num_beams: 6000
spatial_jitter: 1
condition_steps: 10000
unknown_threshold: 0.1
beam_independence: true
