map_topic: "/map"
mi_topic: "/mi"
condition_topic: "/condition_mi"
reset_condition_topic: "/reset_condition_mi"

num_beams: 600
condition_steps: 50000

noise_dev: 0
noise_truncation: 4 # Number of dev before truncation
noise_integration_step: 0.25

visualize: true
visualize_more: false
mi_map_topic: "/mi_map"
binary_map_topic: "/binary_map"
conditional_map_topic: "/conditional_map"
p_not_measured_map_topic: "/p_not_measured_map"
click_condition_topic: "/clicked_point"
