map_topic: "/map"
mi_topic: "/mi"
condition_topic: "/condition_mi"
reset_condition_topic: "/reset_condition_mi"

num_beams: 600
condition_steps: 50000
noise_l: 999999999

visualize: true
visualize_more: true
mi_map_topic: "/mi_map"
p_not_measured_map_topic: "/p_not_measured_map"
click_condition_topic: "/clicked_point"
